name: Test
on:
  pull_request:
  push:
    branches: [master]
jobs:
  btests:
    name: Run btests on ${{ matrix.zeek_container }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        zeek_container: ["zeek/zeek:lts", "zeek/zeek:latest", "zeek/zeek-dev:latest"]
    container: ${{ matrix.zeek_container }}
    steps:
        - name: Checkout Project
          uses: actions/checkout@v3

        - name: Install Golang and build deps
          run: | 
            apt-get update
            apt-get install golang libssl-dev -y    

        - name: Run btests
          run: |
            cd $GITHUB_WORKSPACE/tests
            btest -v -D
